{"content": {"suites": {"0": {"status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 1, "total_error": 0}, "tests": {"0": {"status": "FAIL", "message": "       pika.exceptions.ChannelClosedByBroker: (406, \"PRECONDITION_FAILED - inequivalent arg 'durable' for queue 'Ordering' in vhost '/': received 'false' but current is 'true'\")\n       BaseException: There were problem to count the number of messages.\n       Exception is: (406, \"PRECONDITION_FAILED - inequivalent arg 'durable' for queue 'Ordering' in vhost '/': received 'false' but current is 'true'\")\n", "test_name": "test_valid_message_consumption_rate", "rerun": "0"}}, "suite_name": "tests/suites/test_scalability_suite.py"}}}, "date": "March 14, 2023", "start_time": 1678812570.1671743, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "0", "fail": "1", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "1"}