{"content": {"suites": {"0": {"status": {"total_pass": 1, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 1, "total_error": 0}, "tests": {"0": {"status": "FAIL", "message": "   assert 400 == 200\n    +  where 400 = <Response [400]>.status_code\n    +    where <Response [400]> = <bound method OrderingAPI.cancel_order of <utils.api.ordering_api.OrderingAPI object at 0x00000217D372ADD0>>(0)\n    +      where <bound method OrderingAPI.cancel_order of <utils.api.ordering_api.OrderingAPI object at 0x00000217D372ADD0>> = <utils.api.ordering_api.OrderingAPI object at 0x00000217D372ADD0>.cancel_order\n    +      and   0 = Simulator.CURRENT_ORDER_ID\n", "test_name": "test_cancel_api_request_scenario", "rerun": "0"}, "1": {"status": "PASS", "message": "", "test_name": "test_cancel_invalid_auth_api_request_scenario", "rerun": "0"}}, "suite_name": "test_order_tracking.py"}}}, "date": "March 13, 2023", "start_time": 1678722047.149928, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "1", "fail": "1", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "2"}